<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport"
          content="width = device-width, initial-scale = 1.0">
    <link href="../bootstrap/bootstrap.min.css"
          rel="stylesheet">
    <link href="../style/template.css"
          rel="stylesheet">
</head>
<body>
<header class="container-fluid">
    <div class="row h-auto vh-25">
        <div class="col d-flex justify-content-center align-items-center">
            <img src="/img/svg/logo.svg" alt="Logo" class="img-fluid logo"><br>
            <h1 class="text-center mx-3 my-0 head-text">Рукастые ребята со светлыми лицами</h1>
        </div>
        <nav>
            <ul id="nav3">
                <li><a href="../static/index.html">Главная</a></li>
                <li><a href="../templates/files.ftlh">Файлы</a></li>
                <li><a href="../templates/products.ftlh">Мерч</a></li>
            </ul>
        </nav>
    </div>
</header>


<footer class="container-fluid">
    <div class="row foo">
        <div class="col col-md-4 col-lg-4">
            <h4 class="text-white">Мы в соцсетях:</h4><br>
            <a href="https://t.me/makers2fron" class="text-white">Телеграм-канал</a><br><br>
            <a href="https://t.me/concillor_bot" class="text-white">Телеграм-бот</a>
        </div>

        <div class="col col-md-4 col-lg-4">
            <a href="/donat.html" class="text-white">Предложить файл</a><br><br>
            <a href="../templates/send-files.ftlh" class="text-white">Поддержать проект</a>
        </div>

        <div class="col col-md-4 col-lg-4">
            <h4 class="text-white text-end">Разработчик:</h4><br>
            <img href="https://t.me/regulexper" class="qr" src="/img/svg/developer_qr.svg" alt=" ">
        </div>
    </div>
</footer>
<script src="/bootstrap/bootstrap.bundle.min.js"></script>
</body>
</html>